-- MySQL Script generated by MySQL Workbench
-- Sat Sep  7 15:50:30 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Motos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Motos` (
  `idMotos` INT NOT NULL AUTO_INCREMENT,
  `modelo` VARCHAR(45) NULL,
  `anno` YEAR NULL,
  `color` CHAR NULL,
  `cilindradas` INT NULL,
  PRIMARY KEY (`idMotos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MomentosMoto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MomentosMoto` (
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `idMotos` INT NOT NULL,
  `marcha` INT  NULL,
  `velocidad` INT  NULL,
  PRIMARY KEY (`fecha`, `hora`, `idMotos`),
  INDEX `fk_MomentosMoto_Motos_idx` (`idMotos` ASC) VISIBLE,
  CONSTRAINT `fk_MomentosMoto_Motos`
    FOREIGN KEY (`idMotos`)
    REFERENCES `mydb`.`Motos` (`idMotos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
